# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 367d9ec298b78848d73e6238983cc459c4ac0ba5a32ac5754b02f774c65036302ac0ef38924f36c21442bc5ae1f115d5331fa71266493ec643cf4362e13783fc

test:
  secret_key_base: 4d5cab167940073944c020814980c8e0d1910804d688d248d67fbcdb61526a22dc85cf29aa654a8844844466914cfe2789a3396e13622456d822ce66682e6329

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
